// Generated by scripts/build.py from the fixed original sources.
export const CORPUS_PIN = Object.freeze({"commit": "05ee6bb05982289dbe00c4187b9d54cf90e2e276", "indexSha256": "669831b130fceebfa87bdcacea2497e04962be47e47729181c01f8c93e9f8a1f", "indexBytes": 338554, "documentCount": 148, "totalBytes": 3425888});
