import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,mkdir,symlink,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {createReview,readRequest,unpackResponse,verifyHandoff,reviewHtml,LIMITS} from '../create-review.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
async function fixture(){const dir=await mkdtemp(resolve(tmpdir(),'nft-review-test-'));const svg=Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M10 0L20 20H0Z"/></svg>');const binary=Buffer.alloc(8100);for(let i=0;i<binary.length;i++)binary[i]=(i*61+13)%256;await writeFile(resolve(dir,'cover.svg'),svg);await writeFile(resolve(dir,'payload.bin'),binary);const value={mode:'nft',name:'Exact review fixture',description:'No wallet or chain action.',coverIndex:0,files:[{path:'cover.svg',name:'cover.svg',mediaType:'image/svg+xml'},{path:'payload.bin',name:'payload.bin',mediaType:'application/octet-stream'}]};const request=resolve(dir,'request.json');await writeFile(request,JSON.stringify(value));return {dir,request,value,svg,binary};}
test('real local SDK saves complete large exact intent/link and inert HTML without overwrite',async()=>{const f=await fixture();try{const out=resolve(f.dir,'fresh-output'),receipt=await createReview(f.request,out);assert.equal(receipt.rawBytes,f.svg.length+f.binary.length);assert(receipt.reviewUrlCharacters>15000);assert.deepEqual(receipt.mcpCalls,['studio_capabilities','create_mint_intent','verify_mint_intent']);assert.equal(receipt.signed,false);assert.equal(receipt.submitted,false);for(const row of receipt.files){const bytes=await readFile(resolve(out,row.name));assert.equal(bytes.length,row.bytes);assert.equal(sha(bytes),row.sha256);}const packet=JSON.parse(await readFile(resolve(out,'intent.json'),'utf8')),url=(await readFile(resolve(out,'review-url.txt'),'utf8')).trimEnd(),html=await readFile(resolve(out,'review.html'),'utf8');assert.deepEqual(JSON.parse(Buffer.from(new URL(url).hash.slice('#mint=v1.'.length),'base64url')),packet);assert.deepEqual(Buffer.from(packet.bundle.files[1].uri.split(',')[1],'base64'),f.binary);assert(!html.includes('<script'));assert(html.includes(url.replaceAll('&','&amp;')));const before=await readFile(resolve(out,'receipt.json'));await assert.rejects(createReview(f.request,out),/already exists/);assert.deepEqual(await readFile(resolve(out,'receipt.json')),before);}finally{await rm(f.dir,{recursive:true,force:true});}});
test('real local SDK preserves explicit cover reorder, Unicode and percent-encoded text',async()=>{const f=await fixture();try{await writeFile(resolve(f.dir,'note.txt'),'A safe plain text note.');const value={mode:'nft',name:'星 <review>',coverIndex:1,files:[{path:'note.txt',name:'note.txt',mediaType:'text/plain'},f.value.files[0]]};await writeFile(f.request,JSON.stringify(value));const r=await createReview(f.request,resolve(f.dir,'reordered'));const packet=JSON.parse(await readFile(resolve(r.outputDirectory,'intent.json'),'utf8'));assert.equal(packet.bundle.files[0].name,'cover.svg');assert.equal(packet.bundle.files[1].name,'note.txt');const html=await readFile(resolve(r.outputDirectory,'review.html'),'utf8');assert(html.includes('星 &lt;review&gt;'));}finally{await rm(f.dir,{recursive:true,force:true});}});
test('explicit input bounds reject extra fields, URL, symlink, directory and excessive bytes',async()=>{const f=await fixture();try{const cases=[{...f.value,unknown:true},{...f.value,coverIndex:9},{...f.value,name:'\ud800'},{...f.value,files:[{...f.value.files[0],path:'https://example.invalid/cover.svg'}]},{...f.value,files:[{...f.value.files[0],path:'//server/share/file.svg'}]},{...f.value,files:[{...f.value.files[0],path:'.'}]},{...f.value,files:[]}];await writeFile(resolve(f.dir,'huge.bin'),Buffer.alloc(12001));cases.push({...f.value,files:[{...f.value.files[0],path:'huge.bin'}]});if(process.platform!=='win32'){await symlink(resolve(f.dir,'cover.svg'),resolve(f.dir,'alias.svg'));cases.push({...f.value,files:[{...f.value.files[0],path:'alias.svg'}]});}for(const v of cases){await writeFile(f.request,JSON.stringify(v));await assert.rejects(readRequest(f.request));}await writeFile(f.request,' '.repeat(LIMITS.requestBytes+1));await assert.rejects(readRequest(f.request));await writeFile(f.request,Buffer.from([0xff]));await assert.rejects(readRequest(f.request));}finally{await rm(f.dir,{recursive:true,force:true});}});
test('response bound and duplicate representation disagreement fail closed; HTML escapes inert text',()=>{assert.throws(()=>unpackResponse({content:[{type:'text',text:'x'.repeat(524289)}]}),/512 KiB/);assert.throws(()=>unpackResponse({content:[{type:'text',text:'{"a":1}'}],structuredContent:{a:2}}));assert.throws(()=>unpackResponse({isError:true,content:[{type:'text',text:'input'}]}));const html=reviewHtml('<img onerror=alert(1)>','https://example.invalid/?a="<&');assert(!html.includes('<img'));assert(!html.includes('<script'));assert(html.includes('default-src'));});
test('independent verifier rejects changed packet/hash/file/link even with matching server echo',async()=>{const f=await fixture();try{const args=await readRequest(f.request),receipt=await createReview(f.request,resolve(f.dir,'integrity')),intent=JSON.parse(await readFile(resolve(receipt.outputDirectory,'intent.json'),'utf8')),url=(await readFile(resolve(receipt.outputDirectory,'review-url.txt'),'utf8')).trimEnd();const good={intent,packetJson:JSON.stringify(intent,null,2),review:{url}};assert.deepEqual(verifyHandoff(good,{valid:true,intent},args),intent);for(const change of [x=>x.intent.intentHash='00'.repeat(32),x=>x.intent.bundle.files[0].uri+='x',x=>x.intent.bundle.name+='changed',x=>x.review.url=x.review.url.slice(0,-1),x=>x.review.url=x.review.url.replace('beacnpool.github.io','example.invalid')]){const bad=structuredClone(good);change(bad);bad.packetJson=JSON.stringify(bad.intent);assert.throws(()=>verifyHandoff(bad,{valid:true,intent:bad.intent},args));}}finally{await rm(f.dir,{recursive:true,force:true});}});

test('real SDK supports data intent without a cover and makes no transaction',async()=>{const f=await fixture();try{const request={mode:'data',name:'Data fixture',files:[f.value.files[1]]};await writeFile(f.request,JSON.stringify(request));const r=await createReview(f.request,resolve(f.dir,'data-output'));const packet=JSON.parse(await readFile(resolve(r.outputDirectory,'intent.json'),'utf8'));assert.equal(packet.mode,'data');assert.equal(packet.bundle.cover,false);assert.equal(r.walletConnected,false);assert.equal(r.signed,false);assert.equal(r.submitted,false);}finally{await rm(f.dir,{recursive:true,force:true});}});
